language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env: VENDOR_DIR = ~/nkostadinov/yii2-user/vendor

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0"
  # codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
  - travis_retry composer install --prefer-dist

before_script:
  - ls -la
  - env
  - pwd
#  - codecept build
  - ~/.composer/vendor/bin/codecept build
script:
  - php -S localhost:8080 > /dev/null 2>&1 &
  - ~/.composer/vendor/bin/codecept run

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover